stages:
  - build-deploy

build-deploy:
  stage: build-deploy
  tags:
    - development
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  only:
    - dev-deployment
  script:
    - docker compose --env-file /home/env/.env.rj up --build -d

build-staging:
  stage: build-deploy
  tags:
    - staging
  before_script:
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  only:
    - staging
  script:
    - docker compose --env-file /home/env/.env.rj up --build -d
