services:
  adameds-rj:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    image: adameds/rj-service:dev
    container_name: adameds-rj
    ports:
      - 8088:8088
    restart: always
    networks:
      - rj-network
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
    volumes:
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-rj/private.key
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-rj/public.key
      - type: bind
        source: /home/admin/adameds/.env.vault
        target: /adameds-rj/.env.vault
networks:
  rj-network:
    driver: bridge