services:
  adameds-rj:
    image: adameds/rj-service:dev
    container_name: adameds-rj
    ports:
      - 8088:8088
    restart: always
    networks:
      - rj-network
    environment:
      # db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      # redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DATABASE}

    volumes:
      - type: bind
        source: /home/admin/adameds/private.key
        target: /adameds-rj/private.key
      - type: bind
        source: /home/admin/adameds/public.key
        target: /adameds-rj/public.key
networks:
  rj-network:
    driver: bridge